---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alertkube.fullname" . }}
  labels: {{- include "alertkube.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "alertkube.fullname" . }}
  labels: {{- include "alertkube.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "pods/log", "events", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "alertkube.fullname" . }}
  labels: {{- include "alertkube.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "alertkube.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "alertkube.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
