{{- if not .Values.slack.webhookUrlSecretKeyRef.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertkube.fullname" . }}
  labels: {{- include "alertkube.labels" . | nindent 4 }}
type: Opaque
data:
  slackWebhookUrl: {{ required "slack.webhookUrl required when secretKeyRef not set" .Values.slack.webhookUrl | b64enc | quote }}
{{- end }}
