{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertkube.fullname" . }}-metrics
  labels: {{- include "alertkube.labels" . | nindent 4 }}
spec:
  selector: {{- include "alertkube.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
{{- end }}
