//go:build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.
//
// Hand-maintained rather than controller-gen-generated: the types are small and
// stable, and adding controller-gen to the toolchain for three structs would
// pull the controller-runtime ecosystem we deliberately avoid (ADR-0001). If
// these types grow, switch to controller-gen and delete this file.

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SilenceSpec) DeepCopyInto(out *SilenceSpec) {
	*out = *in
	if in.Matchers != nil {
		m := make(map[string]string, len(in.Matchers))
		for k, v := range in.Matchers {
			m[k] = v
		}
		out.Matchers = m
	}
}

// DeepCopy copies the receiver, creating a new SilenceSpec.
func (in *SilenceSpec) DeepCopy() *SilenceSpec {
	if in == nil {
		return nil
	}
	out := new(SilenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *Silence) DeepCopyInto(out *Silence) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy copies the receiver, creating a new Silence.
func (in *Silence) DeepCopy() *Silence {
	if in == nil {
		return nil
	}
	out := new(Silence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of the object.
func (in *Silence) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out. in must be non-nil.
func (in *SilenceList) DeepCopyInto(out *SilenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		items := make([]Silence, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&items[i])
		}
		out.Items = items
	}
}

// DeepCopy copies the receiver, creating a new SilenceList.
func (in *SilenceList) DeepCopy() *SilenceList {
	if in == nil {
		return nil
	}
	out := new(SilenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generically typed copy of the object.
func (in *SilenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
